notification:
    mattermost:
        enabled: true # mmSender? ??? ? ??, false? ??? ?? ???
        webhook-url:
        channel: # ?? ??? ??? ?? ?? ??? ??? ?? ? ????
        pretext: # attachments? ??? ??? ?? ?? ??? ??
        color: # attachment? ?? ??? ??. default=red
        author-name: # attachment? ??? ??? ??
        author-icon: # author-icon ??? ?? ???? url??
        footer: # attachment? ??? ?? ??. default=?? ??
        props:
            card:

thread:
    pool:
        size: 2